- hosts: localhost
  become: true
  gather_facts: no
  remote_user: vagrant

  tasks:
    
    - name: finding the value
      copy: 
        src: "index.html"
        dest: "/var/www/html/index.html"
